### ISSUE TITLE
Redesign top hero banner

### ISSUE THREAD

**Issue by dohaki** [seichris/santa-landingpage#4]
## Problem
The position of the hero text is fixed and it feels a bit weird to that it is disconnected from the call to action buttons.

## Solution
Change the position to be not fixed anymore and add buttons? Maybe smth like this
![screenshot from 2018-12-01 21-53-27](https://user-images.githubusercontent.com/17645687/49332811-424c1180-f5b4-11e8-8745-c1650dd511e2.png)

**Comment by seichris** [comment]
made some changes for better readability.
@dakingha69 could you change the background blur from 15 to 5, when the site is scrolled down? Its in the css for '.background-image'

**Comment by dohaki** [comment]
ok sure can do that

**Comment by seichris** [comment]
solved
